name: Java + Playwright + Allure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Устанавливаем JDK
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      # 3. Ставим зависимости Playwright (браузеры)
      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      # 4. Запускаем тесты
      - name: Run tests with Maven
        run: mvn clean test

      # 5. Генерируем Allure-отчёт
      - name: Generate Allure Report
        run: mvn allure:report

      # 6. Копируем отчёт в docs/
      - name: Move Allure report to docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r target/site/allure-maven-plugin/* docs/

      # 7. Деплой отчёта в main/docs (для GitHub Pages)
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./docs
          keep_files: true
