name: Java + Playwright CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверка кода
      - uses: actions/checkout@v4

      # 2. Настройка JDK
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      # 3. Кэш Maven зависимостей
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Прогон тестов Maven
      - name: Build and test with Maven
        run: mvn -B -e -X clean test

      # 5. Загрузка surefire отчетов как артефакт
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      # 6. Установка Allure CLI напрямую
      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip -q allure-2.27.0.zip -d /tmp/
          echo "/tmp/allure-2.27.0/bin" >> $GITHUB_PATH

      # 7. Генерация Allure отчета
      - name: Generate Allure Report
        run: |
          allure generate target/allure-results --clean -o target/allure-report

      # 8. Загрузка Allure отчета как артефакт
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
