name: Java + Playwright + Allure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Установка JDK
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      # 3. Установка Playwright (браузеры)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 4. Запуск тестов
      - name: Run tests
        run: mvn clean test

      # 5. Генерация Allure отчёта
      - name: Generate Allure Report
        run: mvn allure:report

      # 6. Деплой Allure-отчёта в GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/allure-maven-plugin
