name: Java Playwright Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install"

      - name: Build and run tests
        run: mvn clean test

      - name: Install Allure CLI (no PPA)
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.29.1/allure-2.29.1.tgz
          tar -xvzf allure-2.29.1.tgz
          sudo mv allure-2.29.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Debug allure-results
        run: |
          echo "Listing allure-results folder:"
          ls -l target/allure-results || echo "No results dir"
          echo "----"
          find target/allure-results -type f -maxdepth 1 || echo "No files"

      - name: Generate Allure report
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/allure-report
